// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiixqgpxababepvpkqob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaXhxZ3B4YWJhYmVwdnBrcW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzAyMDMsImV4cCI6MjA2NDcwNjIwM30.odZ1n5rdbVhSkE9Sf7fcJiyhx8gQpVO1mf3AvDyAjvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);